version: '3.8'

services:
  openproject:
    image: openproject/openproject:14
    container_name: my-openproject
    ports:
      - "${PORT}:80"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_ENV=production
    volumes:
      - .:/app/plugins/openproject-jira_sync
      - ./Gemfile.plugins:/app/Gemfile.plugins
